services:
  model-service:
    build:
      https://github.com/remla24-team3/model-service.git
    volumes:
      - ./model:/app/model
    ports:
      - 105:105

  app-frontend:
    build:
      https://github.com/remla24-team3/app.git#:frontend
    ports:
      - 3000:3000

  app-service:
    build:
      https://github.com/remla24-team3/app.git#:service
    ports:
      - 106:106