{
 "title": "app-service-monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active Sessions",
   "type": "timeseries",
   "description": "This query gives you the current number of active sessions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "active_sessions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Prediction Requests Rate",
   "type": "timeseries",
   "description": "This query calculates the rate of prediction requests per second over the last minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(prediction_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests Rate",
   "type": "timeseries",
   "description": "This query calculates the rate of HTTP requests per second over the last minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "description": "This query gives you the total number of HTTP requests processed by your application.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Processing Time",
   "type": "timeseries",
   "description": "This query calculates the 95th percentile of request processing times over the last 5 minutes. The histogram_quantile function is used to get quantiles from histogram data.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_processing_seconds_bucket[5m])) by (le))\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}