apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
      - name: app-service
        image: ghcr.io/remla24-team3/app-service:test
        ports:
        - containerPort: 106
        env:
        - name: MODEL_SERVICE
          value: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local/model

---

apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-service-monitor
spec:
  selector:
    app: app-service
  ports:
    - name: http
      protocol: TCP
      port: 106
      targetPort: 106
  type: LoadBalancer

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-service-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: app-service-monitor
  endpoints:
  - interval: 15s