# TODO: We need to access this through minikube tunnel

# TODO: "The custom routing is not random. Repeated requests from the same origin have a stable routing" 
# So probably we want to use the user-token here, to do the routing

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"  # Accepts requests from any host

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myapp-virtualservice
spec:
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: "/"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: app-frontend
        port:
          number: 3000
  - match:
    - uri:
        prefix: "/backend/"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: app-service
        port:
          number: 106
  - match:
    - uri:
        prefix: "/model/"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: model-service
        port:
          number: 105
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: myapp-destinationrule
spec:
  host: "*"
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: app-frontend
    labels:
      app: app-frontend
  - name: app-service
    labels:
      app: app-service
  - name: model-service
    labels:
      app: model-service