apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: myapp-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-frontend-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - myapp-gateway
  http:
  - match:
    - uri:
        exact: "/"
    route:
    - destination:
        host: app-frontend
        subset: v1
        port:
          number: 3000
      weight: 90
    - destination:
        host: app-frontend
        subset: v2
        port:
          number: 3000
      weight: 10
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-service-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - myapp-gateway
  http:
  - match:
    - uri:
        prefix: "/backend"
    route:
    - destination:
        host: app-service
        port:
          number: 106
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-frontend
spec:
  host: app-frontend
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2

