apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-service-monitor
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app: app-service
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
    scheme: http
