apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  selector:
    app: myapp
  ports:
    - name: model-service
      protocol: TCP
      port: 105
      targetPort: 105

---
apiVersion: v1
kind: Service
metadata:
  name: app-frontend-service
spec:
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: myapp
  ports:
    - name: service
      protocol: TCP
      port: 106
      targetPort: 106
